name: Build image and push to ghcr.io

on:
  push:
    branches:
      - main

    tags:
      - v*

    paths-ignore:
      - "**/*.txt"
      - "**/*.md"
      - "**/LICENSE"
      - "**.git*"

  pull_request:
    paths-ignore:
      - "**/*.txt"
      - "**/*.md"
      - "**/LICENSE"
      - "**.git*"

env:
  IMAGE_NAME: fetch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Run tests
        run: |
          echo "Not implemented yet"

  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.1.1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }} -buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Find IMAGE_ID
        id: id
        run: |
          IMAGE_ID=ghcr.io/${{ github.actor }}/${IMAGE_NAME}

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr "[A-Z]" "[a-z]")

          echo IMAGE_ID=${IMAGE_ID}

      - name: Find VERSION
        id: version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e "s,.*/\(.*\),\1,")

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo ${VERSION} | sed -e "s/^v//")

          # Use Docker "latest" tag convention
          [ "${VERSION}" == "main" ] && VERSION=latest

          echo VERSION=${VERSION}

      - name: test
        run: |
          echo ${{ steps.id.outputs.IMAGE_ID }}:${{ steps.version.outputs.VERSION }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v2.3.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.id.outputs.IMAGE_ID }}:${{ steps.version.outputs.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
